import type { Metadata } from 'next';
import Script from 'next/script';
import localFont from 'next/font/local';
import AuthProvider from '@/components/AuthProvider';

import './globals.css';
import Notice from '@/components/Notice';

export const API = `//dapi.kakao.com/v2/maps/sdk.js?appkey=${process.env.NEXT_PUBLIC_KAKAO_APP_KEY}&libraries=services,clusterer&autoload=false`;

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script src={API} strategy='beforeInteractive' />
        <Script
          async
          src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-YOUR_ADSENSE_ID' // ⭐️ YOUR_ADSENSE_ID를 실제 ID로 변경하세요.
          crossOrigin='anonymous'
          strategy='lazyOnload' // 페이지 로드 후 스크립트 로딩 (최적화)
        />
        <AuthProvider>
          <Notice />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
